In [2]:
import numpy as np
np.pi

3.141592653589793

In [9]:
#1. Constructeur un tableau numpy qui contient les éléments suivants : 1,5,7,8.
a=np.array([1,5,7,8])
a

array([1, 5, 7, 8])

In [10]:
#2. Constructeur un tableau numpy qui contient les éléments suivants :
#1,2,3,4,5,6,7,8,9

b=np.arange(1,10,1)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#3. Créer un tableau de 10 éléments rempli de 0

b= np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#4. Créer un tableau de 2 lignes 5 colonnes rempli de 0
b=np.zeros((2,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
#5. Créer un tableau de 10 éléments rempli de 1
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
#6. Créer un tableau de 2 lignes 5 colonnes rempli de 1
b=np.ones((2,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#7. Créer un tableau de 10 éléments rempli 8.5
b=np.full(10,8.5)
b

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [29]:
#8. Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus

b=np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#9. Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs
#allant de 1 à 9 inclus

b=np.arange(1,10)
a= b.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#10.Créer une matrice identité de 4 lignes 4 colonnes

taille=4
b = np.eye(taille)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#11. Tableau rempli de valeurs aléatoires normales centrées en zéro

shape = (3, 3)
ecart_type = 1.0
b = np.random.normal(0, ecart_type, shape)
b

array([[-1.26145647,  0.60907888,  0.4059431 ],
       [-0.5533992 , -0.93211859, -0.1337048 ],
       [ 2.25327796,  0.57785017, -0.64179929]])

In [40]:
#12.Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et 10
min = 1
max = 10
nombre = 20
b=np.random.randint(min, max + 1, nombre)
b


array([ 8,  7,  9,  7,  3,  7,  2,  2, 10,  5,  5,  4,  3,  8,  6,  2, 10,
        5,  6,  8])

In [41]:
#13.Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes

matrice=b.reshape(4,5)
matrice

array([[ 8,  7,  9,  7,  3],
       [ 7,  2,  2, 10,  5],
       [ 5,  4,  3,  8,  6],
       [ 2, 10,  5,  6,  8]])

In [43]:
#14.Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale
b = np.linspace(0, 1, 5)
b

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# EXERCICE 2

Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]]).

In [47]:
#1. Afficher le nombre de lignes et de colonnes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
ligne, colonne = a.shape
print("le nombre de ligne est:",ligne)
print("le nombre de ligne est:",colonne)

le nombre de ligne est: 3
le nombre de ligne est: 3


In [50]:
print("le nombre de ligne est:",np.size(a,0))

le nombre de ligne est: 3


In [51]:
print("le nombre de colonne est:",np.size(a,1))

le nombre de colonne est: 3


In [52]:
#2. Afficher la dimension de mon tableau
dim=a.ndim
dim

2

In [53]:
#3. Afficher le nombre d'élément de mon tableau
nombre_element = a.size
nombre_element

9

In [57]:
#4. Afficher le type des éléments du tableau

type_element = a.dtype
type_element

dtype('int32')

# EXERCICE 3


In [5]:
#1. afficher la valeur 5 qui est dans le tablea
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
element = a[1, 1]
element

5

In [6]:
2. Remplacer le 5 qui est dans le tableau par 0
a[1, 1] = 0
a

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [8]:
#3. afficher les chiffres 3, 6 et 9 du tableau

chiffres = [a[0, 2], a[1, 2], a[2, 2]]
chiffres

[3, 6, 9]

In [16]:
#4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
tableau_random =np.random.randint(0, 10, size=(4, 3))
tableau_random

array([[9, 7, 5],
       [1, 5, 7],
       [0, 0, 6],
       [2, 7, 2]])

In [19]:
#5. Vérifier qu’il y a des nombres inférieur à 5
nombres_inferieurs_a_5 = tableau_random < 5
nombres_inferieurs_a_5

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [20]:
#6. Remplacer les nombres inférieurs à 5 par 0
tableau_random[nombres_inferieurs_a_5] = 0
tableau_random

array([[9, 7, 5],
       [0, 5, 7],
       [0, 0, 6],
       [0, 7, 0]])

# EXERCICE 4

In [4]:
#1. Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers aléatoires compris entre 0 et 9
tableau_random =np.random.randint(0, 10, size=(4, 3))
tableau_random

array([[2, 6, 2],
       [3, 2, 8],
       [1, 6, 1],
       [5, 8, 7]])

In [6]:
#2. Quel est le type des éléments du tableau ?
type_element = tableau_random.dtype
type_element

dtype('int32')

In [9]:
#3. Changer de type des éléments du tableau en float32
type_element = 'float32'
type_element

'float32'

In [11]:
tableau_random.dtype = type_element
tableau_random.dtype

dtype('float32')

In [13]:
#4. Ajouter le chiffre 3 à la fin du tableau à une dimension
np.append(tableau_random,3)

array([2.80259693e-45, 8.40779079e-45, 2.80259693e-45, 4.20389539e-45,
       2.80259693e-45, 1.12103877e-44, 1.40129846e-45, 8.40779079e-45,
       1.40129846e-45, 7.00649232e-45, 1.12103877e-44, 9.80908925e-45,
       3.00000000e+00])

In [14]:
#5. Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
a=tableau_random.reshape(3,4)
a

array([[2.8e-45, 8.4e-45, 2.8e-45, 4.2e-45],
       [2.8e-45, 1.1e-44, 1.4e-45, 8.4e-45],
       [1.4e-45, 7.0e-45, 1.1e-44, 9.8e-45]], dtype=float32)

In [17]:
#6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b =np.random.randint(1, 13, size=(3, 4))
b

array([[ 6, 12,  1, 12],
       [ 4,  8, 10,  1],
       [ 8,  6,  5,  6]])

In [19]:
#7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux “a” et “b” dans le sens horizontaleµ
c = np.hstack((a, b))
c

array([[2.80259693e-45, 8.40779079e-45, 2.80259693e-45, 4.20389539e-45,
        6.00000000e+00, 1.20000000e+01, 1.00000000e+00, 1.20000000e+01],
       [2.80259693e-45, 1.12103877e-44, 1.40129846e-45, 8.40779079e-45,
        4.00000000e+00, 8.00000000e+00, 1.00000000e+01, 1.00000000e+00],
       [1.40129846e-45, 7.00649232e-45, 1.12103877e-44, 9.80908925e-45,
        8.00000000e+00, 6.00000000e+00, 5.00000000e+00, 6.00000000e+00]])

In [20]:
#8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux “a” et “b” dans le sens vertical
d = np.vstack((a, b))
d

array([[2.80259693e-45, 8.40779079e-45, 2.80259693e-45, 4.20389539e-45],
       [2.80259693e-45, 1.12103877e-44, 1.40129846e-45, 8.40779079e-45],
       [1.40129846e-45, 7.00649232e-45, 1.12103877e-44, 9.80908925e-45],
       [6.00000000e+00, 1.20000000e+01, 1.00000000e+00, 1.20000000e+01],
       [4.00000000e+00, 8.00000000e+00, 1.00000000e+01, 1.00000000e+00],
       [8.00000000e+00, 6.00000000e+00, 5.00000000e+00, 6.00000000e+00]])

In [21]:
#9. Aplatir un tableau “d
d_aplati = d.flatten()
d_aplati 

array([2.80259693e-45, 8.40779079e-45, 2.80259693e-45, 4.20389539e-45,
       2.80259693e-45, 1.12103877e-44, 1.40129846e-45, 8.40779079e-45,
       1.40129846e-45, 7.00649232e-45, 1.12103877e-44, 9.80908925e-45,
       6.00000000e+00, 1.20000000e+01, 1.00000000e+00, 1.20000000e+01,
       4.00000000e+00, 8.00000000e+00, 1.00000000e+01, 1.00000000e+00,
       8.00000000e+00, 6.00000000e+00, 5.00000000e+00, 6.00000000e+00])

In [22]:
# 10.Supprimer dernier élément du tableau
d_aplati[:-1]
d_aplati

array([2.80259693e-45, 8.40779079e-45, 2.80259693e-45, 4.20389539e-45,
       2.80259693e-45, 1.12103877e-44, 1.40129846e-45, 8.40779079e-45,
       1.40129846e-45, 7.00649232e-45, 1.12103877e-44, 9.80908925e-45,
       6.00000000e+00, 1.20000000e+01, 1.00000000e+00, 1.20000000e+01,
       4.00000000e+00, 8.00000000e+00, 1.00000000e+01, 1.00000000e+00,
       8.00000000e+00, 6.00000000e+00, 5.00000000e+00, 6.00000000e+00])

In [23]:
tableau_random[:-1]
tableau_random

array([[2.8e-45, 8.4e-45, 2.8e-45],
       [4.2e-45, 2.8e-45, 1.1e-44],
       [1.4e-45, 8.4e-45, 1.4e-45],
       [7.0e-45, 1.1e-44, 9.8e-45]], dtype=float32)

# EXERCICE NUMPY Statistique avec numpy

Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
#1. Afficher la somme des éléments du tableau
somme= np.sum(a)
somme

7.1e-44

In [25]:
#2. Afficher la somme des éléments du tableau par colonne
somme_colonne = np.sum(a, axis=0)
somme_colonne

array([7.0e-45, 2.7e-44, 1.5e-44, 2.2e-44], dtype=float32)

In [26]:
#3. Afficher la somme des éléments du tableau par ligne
somme_ligne = np.sum(a, axis=0)
somme_ligne

array([7.0e-45, 2.7e-44, 1.5e-44, 2.2e-44], dtype=float32)

In [27]:
#4. Afficher le produit des éléments du tableau par colonne
produit_colonne = np.prod(a, axis=0)
produit_colonne

array([0., 0., 0., 0.], dtype=float32)

In [28]:
#5. Afficher le minimum du tableau
minimum = np.min(a)
minimum

1e-45

In [29]:
#6. Afficher le minimum du tableau
maximum = np.max(a)
maximum

1.1e-44

In [30]:
#7. Afficher la moyenne des éléments du tableau
moyenne = np.mean(a)
moyenne

6e-45

In [32]:
#8. Afficher la variance des éléments du tableau
variance = np.var(a)
variance

0.0

In [33]:
#9. Afficher l’écart type des éléments du tableau
ecart_type = np.std(a)
ecart_type

0.0